### ISSUE TITLE
ASGI throws a traceback when a previously-served file is cached in the server.

### ISSUE THREAD

**Issue by CircuitCodes** [pgjones/quart#102]
The error in question is the `write_eof()` call in the ASGI development server. 

The traceback in full is as follows:
```
[2020-04-14 11:29:29,331] Error in ASGI Framework
Traceback (most recent call last):
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\asyncio\spawn_app.py", line 13, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\utils.py", line 203, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\app.py", line 2059, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\app.py", line 2082, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 31, in __call__
    _raise_exceptions(done)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 233, in _raise_exceptions
    raise task.exception()
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 78, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 93, in _send_response
    await send({"type": "http.response.body", "body": data, "more_body": True})
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\http_stream.py", line 145, in app_send
    await self.send(
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\h11.py", line 130, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\h11.py", line 222, in _send_h11_event
    await self.send(RawData(data=data))
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 88, in protocol_send
    self.writer.write(event.data)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\streams.py", line 341, in write
    self._transport.write(data)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\proactor_events.py", line 337, in write
    raise RuntimeError('write_eof() already called')
RuntimeError: write_eof() already called
[2020-04-14 11:29:31,522] 127.0.0.1:50429 GET /api/library/test.mp3 1.1 206 1455763 2133636
[2020-04-14 11:29:31,553] 127.0.0.1:50429 GET /api/library/test.mp3 1.1 416 146 22934
[2020-04-14 11:30:13,727] 127.0.0.1:50440 GET / 1.1 200 504 21905
[2020-04-14 11:30:14,239] Error in ASGI Framework
Traceback (most recent call last):
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\asyncio\spawn_app.py", line 13, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\utils.py", line 203, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\app.py", line 2059, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\app.py", line 2082, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 31, in __call__
    _raise_exceptions(done)
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 233, in _raise_exceptions
    raise task.exception()
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 78, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\quart\asgi.py", line 93, in _send_response
    await send({"type": "http.response.body", "body": data, "more_body": True})
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\http_stream.py", line 145, in app_send
    await self.send(
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\h11.py", line 130, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\protocol\h11.py", line 222, in _send_h11_event
    await self.send(RawData(data=data))
  File "C:\Users\circu\scoop\apps\python\current\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 88, in protocol_send
    self.writer.write(event.data)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\streams.py", line 341, in write
    self._transport.write(data)
  File "C:\Users\circu\scoop\apps\python\current\lib\asyncio\proactor_events.py", line 337, in write
    raise RuntimeError('write_eof() already called')
RuntimeError: write_eof() already called
```
and the route serving the files:
```py
    # This seems to throw a
    # RuntimeError('Cannot call write() after write_eof()')
    # if the file was already cached by the client
    # when this is called
    @app.route("/api/library/<filename>")
    async def send_file(filename):
        response = await send_from_directory(f"audio", filename)

        await response.make_conditional(request.range)
        return response
```

**Comment by CircuitCodes** [comment]
Note: This seems to be related to our use of HTTP range requests and the [response.wrappers.make_conditional](https://github.com/pgjones/quart/blob/master/src/quart/wrappers/response.py#L382) function.

**Comment by pgjones** [comment]
I think this is fixed with Hypercorn 0.9.5, could you upgrade and try it?

**Comment by CircuitCodes** [comment]
Any way to remove this error in the development ASGI server?

**Comment by pgjones** [comment]
> Any way to remove this error in the development ASGI server?

Note sure what you mean?

**Comment by pgjones** [comment]
I think you are asking when developing with Quart, in this case you can just upgrade Hypercorn and it will be fixed.
