### ISSUE TITLE
quart.abort(405) is broken

### ISSUE THREAD

**Issue by Danstiv** [pgjones/quart#120]
Hello, quart.abort(405) does not work as expected
```
asyncio REPL 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import quart
>>> quart.__version__
'0.14.1'
>>> app = quart.Quart(__name__)
>>> @app.route('/test')
... async def test():
...     quart.abort(int(quart.request.args['code']))
...
>>> t=asyncio.create_task(app.run_task())
>>> [2021-02-24 20:30:30,819] Running on http://127.0.0.1:5000 (CTRL + C to quit)
***another interpreter***
>>> requests.get('http://127.0.0.1:5000/test?code=404')
<Response [404]>
>>> requests.get('http://127.0.0.1:5000/test?code=406')
<Response [406]>
>>> requests.get('http://127.0.0.1:5000/test?code=405')
<Response [500]>
***Exception from first interpreter***
[2021-02-24 20:33:36,570] ERROR in app: Exception on request GET /test
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\quart\app.py", line 1885, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "C:\Python38\lib\site-packages\quart\app.py", line 1933, in dispatch_request
    return await handler(**request_.view_args)
  File "<console>", line 3, in test
  File "C:\Python38\lib\site-packages\quart\exceptions.py", line 199, in abort
    raise error
quart.exceptions.MethodNotAllowed: MethodNotAllowed(405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\quart\app.py", line 1862, in handle_request
    return await self.full_dispatch_request(request_context)
  File "C:\Python38\lib\site-packages\quart\app.py", line 1887, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "C:\Python38\lib\site-packages\quart\app.py", line 1100, in handle_user_exception
    return await self.handle_http_exception(error)
  File "C:\Python38\lib\site-packages\quart\app.py", line 1078, in handle_http_exception
    return error.get_response()
  File "C:\Python38\lib\site-packages\quart\exceptions.py", line 57, in get_response
    return Response(self.get_body(), status=self.status_code, headers=self.get_headers())
  File "C:\Python38\lib\site-packages\quart\exceptions.py", line 127, in get_headers
    headers.update({"Allow": ", ".join(self.allowed_methods)})
TypeError: can only join an iterable
```

**Comment by pgjones** [comment]
Yep, this will be fixed in the next release (will switch to Werkzeug's exceptions)
