### ISSUE TITLE
route default variable not working. 

### ISSUE THREAD

**Issue by gata1526** [pgjones/quart#124]
I migrated from flask and keep getting error about route overlapping.  they work perfectly in flask, but quart make all those routes useless.

**Comment by gata1526** [comment]
@managers.route("/user_manager", defaults={"department": 0, "division": 0, "search": None}, methods=['GET', 'POST'])
@managers.route("/user_manager/<int:department>", defaults={"division": 0, "search": None}, methods=['GET', 'POST'])
@managers.route("/user_manager/<int:department>/<int:division>", defaults={"search": None}, methods=['GET', 'POST'])
@managers.route("/user_manager/<int:department>/<int:division>/<search>", methods=['GET', 'POST'])

**Comment by gata1526** [comment]
I tried to make delete some of those to find the problem, but as soon as there is more than 1 route deffinition it will crash

**Comment by pgjones** [comment]
What version of Quart are you using? (I can't reproduce this error).

**Comment by gata1526** [comment]
the latest one 0.14.1 installed with pip.

**Comment by gata1526** [comment]
I found a better solution for my problem than switching to quart. But I may give it a go later on.

**Comment by pgjones** [comment]
Strange, I can't reproduce this error with 0.14.1. Could it be that you have route functions with the same name?

**Comment by gata1526** [comment]
No they work fine in normal flask. I even had to delete one of my home routes since "  /  " was creating a conflict with " /home " even if they work perfectly in flask. Doesn't seem to be possible to put more than one decorator.

**Comment by pgjones** [comment]
Hmm, really odd, does this work for you?
```python
from quart import Quart                                                                                                                                                                                     
                                                                                                                                                                                                            
app = Quart(__name__)                                                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            
@app.route("/user_manager", defaults={"department": 0, "division": 0, "search": None}, methods=['GET', 'POST'])                                                                                             
@app.route("/user_manager/<int:department>", defaults={"division": 0, "search": None}, methods=['GET', 'POST'])                                                                                               
@app.route("/user_manager/<int:department>/<int:division>", defaults={"search": None}, methods=['GET', 'POST'])                                                                                                 
@app.route("/user_manager/<int:department>/<int:division>/", methods=['GET', 'POST'])                                                                                                                           
async def index():                                                                                                                                                                                          
    return ""                                                                                                                                                                                               
                                                                                                                                                                                                            
app.run()
```

**Comment by gata1526** [comment]
seem to work just like that, but in modules it didn't seem to work. I could try again later this weekend.

Just to make sure. Can I still use synchronous function with quart setup?

**Comment by pgjones** [comment]
Yep, synchronous functions are run in a thread (so as to not block the event loop).

**Comment by gata1526** [comment]
do you have a demo of VS code debugging setup file?

**Comment by gata1526** [comment]
Traceback (most recent call last):
  File "e:\Onedrive\thecorporation\TheCorporation.space\run.py", line 4, in <module>
    app = create_app()
  File "e:\Onedrive\thecorporation\TheCorporation.space\corporation\__init__.py", line 75, in create_app
    app.register_blueprint(main)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 1461, in register_blueprint
    blueprint.register(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 766, in register
    func(state)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 133, in <lambda>
    lambda state: state.add_url_rule(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 830, in add_url_rule
    self.app.add_url_rule(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 647, in add_url_rule
    raise AssertionError(f"Handler is overwriting existing for endpoint {endpoint}")
AssertionError: Handler is overwriting existing for endpoint main.home

**Comment by gata1526** [comment]
@main.route("/")
@main.route("/home")
def home():
    return render_template("home.html")

**Comment by gata1526** [comment]
from quart import render_template, request, Blueprint

**Comment by gata1526** [comment]
I have 2 other template that registered normally, but it seem that having 2 decorator create an error in modules

**Comment by pgjones** [comment]
Given the error I think you must either have two route handlers called `home` (i.e. `def home`) or you are specifying `endpoint="home"` somewhere? I can't find any other way to reproduce your error.

> do you have a demo of VS code debugging setup file?

I don't use VS code so sadly no.

**Comment by gata1526** [comment]
The only thing I did was moving from a working Flask app to Quart. And every place that I use more than one decorator route per function it creates a problem. The problem must be in the blueprint then since it was working when used without module.

**Comment by gata1526** [comment]
@pgjones the problem was the flask patcher that was creating the error, but now I have another one:

Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

**Comment by gata1526** [comment]
Confirm the problem only occur with the patch, but the program doesn't seem to work without it either

**Comment by pgjones** [comment]
Thanks, I think I've fixed this in f9c205ec9d5b2ea9f3f8b04faaf1779e075fb408.

I'll need the request context error traceback to help with that issue.

**Comment by gata1526** [comment]
How do I give that to you?

**Comment by gata1526** [comment]
warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "e:\Onedrive\thecorporation\TheCorporation.space\run.py", line 4, in <module>
    app = create_app()
  File "e:\Onedrive\thecorporation\TheCorporation.space\corporation\__init__.py", line 77, in create_app
    app.register_blueprint(main)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 1461, in register_blueprint
    blueprint.register(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 766, in register
    func(state)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 133, in <lambda>
    lambda state: state.add_url_rule(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\blueprints.py", line 830, in add_url_rule
    self.app.add_url_rule(
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 647, in add_url_rule
    raise AssertionError(f"Handler is overwriting existing for endpoint {endpoint}")
AssertionError: Handler is overwriting existing for endpoint main.home

I have that is it what you need?

**Comment by gata1526** [comment]
from quart import render_template, request, Blueprint
from corporation.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template("home.html")

**Comment by gata1526** [comment]
Not sure I updated quart. I redid the pip install

**Comment by gata1526** [comment]
```
Traceback (most recent call last):
  File "e:\Onedrive\thecorporation\TheCorporation.space\run.py", line 1, in <module>
    from corporation import create_app
  File "e:\Onedrive\thecorporation\TheCorporation.space\corporation\__init__.py", line 3, in <module>
    import quart.flask_patch
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\__init__.py", line 7, in <module>
    from .app import Quart
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 41, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\debug.py", line 8, in <module>
    from .wrappers import Response
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\wrappers\__init__.py", line 3, in <module>
    from .base import BaseRequestWebsocket
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\wrappers\base.py", line 7, in <module>
    from werkzeug.sansio.request import Request as SansIORequest
ModuleNotFoundError: No module named 'werkzeug.sansio'
```

**Comment by gata1526** [comment]
I went to get the github version of it and it start, but I get this error now.
```

[2021-04-16 14:24:57,746] Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2021-04-16 14:25:25,638] Error in ASGI Framework
Traceback (most recent call last):
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hypercorn\asyncio\context.py", line 39, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hypercorn\utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 1808, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\app.py", line 1834, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\asgi.py", line 51, in __call__
    _raise_exceptions(done)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\asgi.py", line 347, in _raise_exceptions
    raise task.exception()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in 
__step
    result = coro.send(None)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\asgi.py", line 102, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 481, in 
wait_for
    return fut.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in 
__step
    result = coro.send(None)
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\asgi.py", line 131, in _send_response
    async for data in response_body:
  File "C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\quart\wrappers\response.py", line 110, in _aiter
    for data in iterable:  # type: ignore
TypeError: 'coroutine' object is not iterable
```

**Comment by gata1526** [comment]
`Executing <Task pending name='Task-6' coro=<observe_changes() running at C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hypercorn\utils.py:136> wait_for=<Future pending cb=[Task.__wakeup()] created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:424> created at C:\Users\gata2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hypercorn\asyncio\run.py:95>`

maybe this could help too

**Comment by pgjones** [comment]
I think this is the `render_template` usage, it must be awaited with quart,

```python
@main.route("/")
@main.route("/home")
async def home():
    return await render_template("home.html")
```

**Comment by gata1526** [comment]
but the function is not asyncronous

**Comment by gata1526** [comment]
@pgjones  update. So doing this doesn't work:

```python
@app.route("/user_manager", defaults={"department": 0, "division": 0, "search": None}, methods=['GET', 'POST'])
@app.route("/user_manager/<int:department>", defaults={"division": 0, "search": None}, methods=['GET', 'POST'])
@app.route("/user_manager/<int:department>/<int:division>", defaults={"search": None}, methods=['GET', 'POST'])
@app.route("/user_manager/<int:department>/<int:division>/", methods=['GET', 'POST'])
async def index():
    return ""
```
but using a single route is working

```python
@app.route("/user_manager/<int:department>/<int:division>/", defaults={"department": 0, "division": 0, "search": None}, methods=['GET', 'POST'])
async def index():
    return ""
```

**Comment by gata1526** [comment]
All seem to work now. Thanks for all the troubleshooting

**Comment by pgjones** [comment]
Great!

**Comment by gata1526** [comment]
I went back to normal flask with asyncio. It was working last time, but it's broke again.
