### ISSUE TITLE
Weird error on page load

### ISSUE THREAD

**Issue by remkohoef** [pgjones/quart#130]
Hi,

So I wrote a simple discord bot and tried making a dashboard for it.
After loggin in it should go to the dashboard that lists all servers. (Note this worked when I ran everything local (127.0.0.1)

This is the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
    sock.connect(address)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1467, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1492, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 968, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1490, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/root/Isha/dashboard.py", line 39, in dashboard
    guild_count = await ipc_client.request("get_guild_count")
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/ipc/client.py", line 99, in request
    await self.init_sock()
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/ipc/client.py", line 63, in init_sock
    self.multicast = await self.session.ws_connect(self.url, autoping=False)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 721, in _ws_connect
    resp = await self.request(method, url,
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:20000 ssl:default [Cannot assign requested address]
Executing <Task pending name='Task-20' coro=<ASGIHTTPConnection.handle_request() running at /usr/local/lib/python3.8/dist-packages/quart/asgi.py:102> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1bde6afbb0>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:507] created at /usr/local/lib/python3.8/dist-packages/quart/asgi.py:46> took 0.111 seconds
[2021-07-05 20:25:28,238] [IPADDRESSTATIREMOVED]:64462 GET /dashboard 1.1 500 158977 132152

```

**Comment by remkohoef** [comment]
Also:

**Comment by pgjones** [comment]
This is an odd one - could it be that the process doesn't have permission to use the port?
