### ISSUE TITLE
send_file not working

### ISSUE THREAD

**Issue by antonstech** [pgjones/quart#138]
So i just wanted to try out the File-Sending so i set up this:
```
from quart import Quart, send_file, send_from_directory

app = Quart(__name__)


@app.route('/')
async def hello():
    return send_file("test.txt")

app.run(debug=True)
```
and i am always getting a 
```
2022-01-05 02:48:13,613] ERROR in app: Exception on request GET /
Traceback (most recent call last):
  File "/media/anton/venv/lib/python3.8/site-packages/quart/app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/media/anton/venv/lib/python3.8/site-packages/quart/app.py", line 1515, in full_dispatch_request
    return await self.finalize_request(result, request_context)
  File "/media/anton/venv/lib/python3.8/site-packages/quart/app.py", line 1572, in finalize_request
    response = await self.make_response(result)
  File "/media/anton/venv/lib/python3.8/site-packages/quart/app.py", line 1474, in make_response
    raise TypeError(f"The response value type ({type(value).__name__}) is not valid")
TypeError: The response value type (coroutine) is not valid
```
Greetings, Anton

**Comment by antonstech** [comment]
Okay yeah i am just fucking lost and i missed the "await" bruh sorry
