### ISSUE TITLE
Jinja2 3.1.0 update breaks Quart

### ISSUE THREAD

**Issue by cquick01** [pgjones/quart#141]
Jinja2 3.1.0 update breaks Quart.

https://jinja.palletsprojects.com/en/3.1.x/changes/

> - Markup and escape should be imported from MarkupSafe.

Am getting error due to `quart.__init__` importing `escape` and `Markup` directly from `jinja2`. They should be imported from `MarkupSafe` instead: https://markupsafe.palletsprojects.com/en/2.1.x/

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "REDACTED ", line 10, in <module>
    from REDACTED import REDACTED 
  File "REDACTED ", line 7, in <module>
    import quart
  File "/home/user/.cache/pypoetry/virtualenvs/REDACTED/lib/python3.9/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/home/user/.cache/pypoetry/virtualenvs/REDACTED/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by kbessemer** [comment]
As a temporary fix, I am using the previous release of jinja2 (3.0.3)

**Comment by cquick01** [comment]
Didn't realize this repo was just a mirror of GitLab.

GitLab issue: https://gitlab.com/pgjones/quart/-/issues/458

Fix Merge Request: https://gitlab.com/pgjones/quart/-/merge_requests/120
