### ISSUE TITLE
Quart 0.16.3 breaks with jinja2 3.1.0

### ISSUE THREAD

**Issue by danilito19** [pgjones/quart#142]
Jinja2 just released 3.1.0 https://pypi.org/project/Jinja2/#history and this breaks quart 0.16.3

To reproduce, simply install `pip install quart`, it should have quart 0.16.3 and jinja2 3.1.0 , start a quart app server, and see
```
python apps/quart_app.py localhost 8000
Traceback (most recent call last):
  File "/Users/dani/vulnpy/apps/quart_app.py", line 3, in <module>
    from quart import Quart, redirect
  File "/Users/dani/testy/lib/python3.9/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/Users/dani/testy/lib/python3.9/site-packages/jinja2/__init__.py)
```

I think the fix can be to pin the jinja2 version or support 3.1.0

**Comment by danilito19** [comment]
fixed in https://gitlab.com/pgjones/quart/-/merge_requests/120
