### ISSUE TITLE
with app.app_context() in thread: AttributeError: __enter__

### ISSUE THREAD

**Issue by Alevsk** [pgjones/quart#56]
Hi, Im using `current_app._get_current_object()` to pass the app object into a thread and execute `app.app_context()` however im facing a run time error regarding: `AttributeError: __enter__`, after some more investigation adding `import quart.flask_patch` to the top of my main module didn't work for me nor defining my own Thread class with `current_app` object attached to it. 

```
class FlaskThread(Thread):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.app = current_app._get_current_object()

  def run(self):
    with self.app.app_context():
        super().run()
```

^ this didn't work for me

My code looks like this:

```
from threading import Thread
from quart import current_app
from flask_mail import Message
from app import mail

def send_async_email(app, msg):
  with app.app_context():
    mail.send(msg)

def send_email(subject, sender, recipients, text_body, html_body, attachments=None, sync=False):
  msg = Message(subject, sender=sender, recipients=recipients)
  msg.body = text_body
  msg.html = html_body
  if attachments:
    for attachment in attachments:
      msg.attach(*attachment)
  if sync:
    mail.send(msg)
  else:
    Thread(
      target=send_async_email,
      args=(current_app._get_current_object(), msg),
    ).start()

```

The issue, as I understand, is happening once the execution reached `with app.app_context():` after that line, the _enter_ method for app will be called but it seems like that method is not implemented in `from quart import current_app`

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/leninarias/go/src/app.theia/account-recovery/venv/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 47, in run
    reraise(*_capture_exception())
  File "/Users/leninarias/go/src/app.theia/account-recovery/venv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/Users/leninarias/go/src/app.theia/account-recovery/venv/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 45, in run
    return old_run(*a, **kw)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/leninarias/go/src/app.theia/account-recovery/app/email.py", line 7, in send_async_email
    with app.app_context():
AttributeError: __enter__
```

I'll continue investigating the issue but I feel like this is an internal issue with Quart (if isn't pardon me, Im still a newbie on python)

**Comment by pgjones** [comment]
This is a common issue with Flask and Quart contexts, you can solve it via the [`copy_current_app_context`](https://pgjones.gitlab.io/quart/contexts.html#tasks-and-contexts) decorator, as so,
```python
Thread(
      target=copy_current_app_context(send_async_email),
      args=(current_app._get_current_object(), msg),
    ).start()
```

The issue is that the context (with Quart 0.7 onwards) is copied for you into different asyncio tasks, however it isn't copied into a different Thread. The explicit usage of the `copy_current_app_context` does so though.

**Comment by slyduda** [comment]
I am getting the following warning: RuntimeWarning: coroutine 'wrapper' was never awaited
  self._target(*self._args, **self._kwargs)

The wrapped function does not run either.

**Comment by pgjones** [comment]
Ah yes as the `copy_current_app_context` returns a coroutine function rather than a function. You need to run an event loop on the other thread. 

Are you trying to run a sync or async function in another thread? Also are you trying to invoke the thread from a sync or async context?

**Comment by slyduda** [comment]
Sync exactly as shown in the example above. I am invoking from an async context within one of the Quart_OpenAPI endpoints:

```
def send_email(_app, message):
    with _app.app_context():
        mail.send(message)

@app.route('/test')
class Test(Resource):
    async def get(self):
        message = Message(sender=app.config.get('MAIL_USERNAME'),
                          recipients=[app.config.get('MAIL_USERNAME')],
                          subject='TEST')

        Thread(
            target=copy_current_app_context(send_email),
            args=(
                current_app._get_current_object(),
                message
            )
        ).start()

        response = {
            'message': 'New registration email sent.'
        }

        return jsonify(response), 200
```

**Comment by slyduda** [comment]
Additionally, this is what I tried to run an event loop on the other thread, but I am still getting the same warning:

```

def send_email(_app, _loop, message):
    with _app.app_context():
        print('====> sending on a separate thread.')
        asyncio.set_event_loop(_loop)
        _loop.run_until_complete(
            mail.send(message)
        )


@app.route('/test')
class Test(Resource):
    async def get(self):
        message = Message(sender=app.config.get('MAIL_USERNAME'),
                          recipients=[app.config.get('MAIL_USERNAME')],
                          subject='TEST')

        thr = Thread(
            target=copy_current_app_context(send_email),
            args=(
                current_app._get_current_object(),
                asyncio.new_event_loop(),
                message
            )
        ).start()

        response = {
            'message': 'New registration email sent.'
        }

        return jsonify(response), 200

```

**Comment by slyduda** [comment]
Sorry to spam, this technique has failed me as well: https://pgjones.gitlab.io/quart/background_tasks.html

**Comment by pgjones** [comment]
Does this work?
```python
from contextvars import copy_context
from functools import partial

async def run_sync(func) -> Any:
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(
        None, copy_context().run, func,
    )

def send_email(message):
    with app.app_context():
        print('====> sending on a separate thread.')
        mail.send(message)

@app.route('/test')
async def get(self):
    message = Message(
        sender=app.config.get('MAIL_USERNAME'),
        recipients=[app.config.get('MAIL_USERNAME')],
        subject='TEST',
    )
    await run_sync(partial(send_email, message))
```
If so it will get a lot easier in the next Quart release (if not I need to do some more work).

**Comment by slyduda** [comment]
Unfortunately, I get the following:

```
 File "app.py", line 100, in send_email
    with app.app_context:
```

**Comment by pgjones** [comment]
Hmm tricky, this then needs to allow the execution of sync code in a thread surrounded by an async context setup. Does this work?
```python
from contextvars import copy_context
from functools import partial

async def run_sync(func) -> Any:
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(
        None, copy_context().run, func,
    )

def send_email(message):
    print('====> sending on a separate thread.')
    mail.send(message)

@app.route('/test')
async def get(self):
    message = Message(
        sender=app.config.get('MAIL_USERNAME'),
        recipients=[app.config.get('MAIL_USERNAME')],
        subject='TEST',
    )
    async with app.app_context():
        await run_sync(partial(send_email, message))
```
I've wrapped the run sync in the app context setup, which should keep it set during the `run_sync` execution. As run_sync copies the context it should also be available in the `send_email` function...

**Comment by slyduda** [comment]
This works! 

Pardon my confusion though, I was under the impression that the intent of the original post was to create a function on a new thread to provide the end user with a response while dealing with the mail server connection asynchronously. With this fix it is still blocking my response. Maybe the confusion stemmed from my choice to make the send mail function synchronous, though I kept getting a never awaited error when attaching it to the thread.

**Comment by pgjones** [comment]
Ah, the above solution ensures that the actual sending of the message doesn't block the event loop thereby allowing the app/server to serve other requests concurrently. To achieve a background send you will need to use a background task as well,
```python
from contextvars import copy_context
from functools import partial

async def run_sync(func) -> Any:
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(
        None, copy_context().run, func,
    )

def send_email(message):
    print('====> sending on a separate thread.')
    mail.send(message)

@app.route('/test')
async def get():
    async def _get():
        message = Message(
            sender=app.config.get('MAIL_USERNAME'),
            recipients=[app.config.get('MAIL_USERNAME')],
            subject='TEST',
        )
        async with app.app_context():
            await run_sync(partial(send_email, message))
    asyncio.ensure_future(_get())
    return "Pending", 201
```

**Comment by slyduda** [comment]
This above code is perfect! Thank you so much for the help.
