### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by crinny** [pgjones/quart#61]
I am trying to migrate to Quart from Flask and I've got some weird problems. So this is a piece of my code:
```
@app.route('/', defaults={'path': ''}, methods=['GET', 'POST'])
@app.route('/<path:path>', methods=['GET', 'POST'])
async def proxy(path):
    form = await request.form.to_dict()
    # Some actions with form
```

But sometimes it raises this error:
```
Traceback (most recent call last):
  File "C:\Users\crinny\PycharmProjects\realmfaker\venv\lib\site-packages\quart\app.py", line 1449, in handle_request
    return await self.full_dispatch_request(request_context)
  File "C:\Users\crinny\PycharmProjects\realmfaker\venv\lib\site-packages\quart\app.py", line 1471, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "C:\Users\crinny\PycharmProjects\realmfaker\venv\lib\site-packages\quart\app.py", line 892, in handle_user_exception
    raise error
  File "C:\Users\crinny\PycharmProjects\realmfaker\venv\lib\site-packages\quart\app.py", line 1469, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "C:\Users\crinny\PycharmProjects\realmfaker\venv\lib\site-packages\quart\app.py", line 1517, in dispatch_request
    return await handler(**request_.view_args)
  File "C:/Users/crinny/PycharmProjects/realmfaker/httprealm_quart.py", line 43, in proxy
    form = await request.form.to_dict()
AttributeError: 'coroutine' object has no attribute 'to_dict'
```

I can not find factors that can let the things break, but I can leave the whole code.

P.S. I am using Python 3.7.2

**Comment by pgjones** [comment]
This is a [common pitfall](https://pgjones.gitlab.io/quart/asyncio.html#common-pitfalls) with the async syntax, if you change `form = await request.form.to_dict()` to `form = (await request.form).to_dict()` it will work fine. The is because everything to the right of the `await` will complete before being awaited and hence it will try to call `to_dict` on a coroutine.

**Comment by crinny** [comment]
@pgjones Thanks for answering! It works like a charm now.
