### ISSUE TITLE
Advice with regards to porting Flask-Classy to be compatible with Quart?

### ISSUE THREAD

**Issue by UNIcodeX** [pgjones/quart#81]
I'm trying to [port Flask-Classy to Quart](https://github.com/unicodex/quart-classy) and am hoping to get your input / advice.

The following is working:
- Import of `quart_classy` and components
- Registration of View class with `app` instance
- Decorators as defined in the `ClassyView.decorators` list
- Access of synchronous views within a defined `ClassyView`

What is not working:
- Access of `asynchronous` view within a defined `ClassyView`

[Code for Quart-Classy module.](https://github.com/UNIcodeX/quart-classy/blob/master/quart_classy.py)

Debug Output:
```shell
==> Class 'TestView' registered.
Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2019-10-30 15:19:24,159] Running on 127.0.0.1:5000 over http (CTRL + C to quit)
==> Decorator hit! Shots fired from 'index'!!
[2019-10-30 15:19:35,151] 127.0.0.1:52736 GET / 1.1 200 333 5871
==> Decorator hit! Shots fired from 'index'!!
[2019-10-30 15:19:39,182] 127.0.0.1:52736 GET /test/ 1.1 200 237 953
==> Decorator hit! Shots fired from 'test_sync'!!
[2019-10-30 15:19:49,391] 127.0.0.1:52739 GET /test/test_sync/ 1.1 200 247 965
==> Decorator hit! Shots fired from 'test_async'!!
Task exception was never retrieved
future: <Task finished coro=<ASGIHTTPConnection.handle_request() done, defined at C:\Users\jaredfields\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\asgi.py:63> exception=TypeError("'coroutine' object is not iterable")>
Traceback (most recent call last):
  File "C:\Users\jaredfields\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\asgi.py", line 70, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Users\jaredfields\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
  File "C:\Users\jaredfields\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\asgi.py", line 82, in _send_response
    async for data in body:
  File "C:\Users\jaredfields\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\wrappers\response.py", line 104, in _aiter
    for data in iterable:  # type: ignore
TypeError: 'coroutine' object is not iterable
[2019-10-30 15:19:52,893] 127.0.0.1:52739 GET /test/test_async/ 1.1 500 - 2944
```

The main Quart web app code:
```python
# test_app.py

from quart import Quart, g, websocket, request, session, render_template_string, render_template, redirect, url_for
from quart_classy import ClassyView, route
from functools import wraps
import asyncio
import time

app = Quart(__name__)

LOGGEDIN = True

def login_required(f):
  @wraps(f)
  def decorated(*args, **kwargs):
    print(f"==> Decorator hit! Shots fired from '{f.__name__}'!!")
    if not LOGGEDIN:
      return redirect(url_for('login'))
    return f(*args, **kwargs)
  return decorated

def navigation():
  return f"""
    <h1>
      <a href="{ url_for('index') }">/</a> 
      <a href="{ url_for('TestView:index') }">test/</a> 
      [<a href="{ url_for('TestView:test_sync') }">test_sync</a> | <a href="{ url_for('TestView:test_async') }">test_async</a>]
      <br/>
      Current Page: { request.url }
    </h1>
    """

@app.route('/login/')
def login():
  return "dummy login page"

@app.route('/')
@login_required
async def index():
  nav = navigation()
  return await render_template_string("""
  <html>
    <head>
      <title>Index</title>
    <head>
    <body>
      {{ locals['nav']|safe }}
    </body>
  </html>
  """, locals=locals())

from classy_view import *

if __name__ == "__main__":
  app.run(debug=True)
```

The `ClassyView`, views:
```python
# classy_view.py

from test_app import *


class TestView(ClassyView):
  decorators = [login_required]

  def index(self):
    return navigation()

  def test_sync(self):
    nav = navigation()
    return nav
  
  async def test_async(self):
    nav = navigation()
    return await render_template_string("""
    <html>
      <head>
        <title>Test - Async</title>
      <head>
      <body>
        {{ locals['nav']|safe }}
      </body>
    </html>
    """, locals=locals())

TestView.register(app)
```

**Comment by UNIcodeX** [comment]
As noted in the ["issue"](https://gitlab.com/pgjones/quart/issues/275) opened on GitLab, I believe Blueprints will provide what I'm needing. I would, however, be interested to know you thoughts on how this could possibly be ported, so I can get an idea of how to possibly port other Flask utilities as necessary.
