### ISSUE TITLE
how to make quart websocket (asyncio.create_task) to work with python3.6?

### ISSUE THREAD

**Issue by c2h2** [pgjones/quart#85]
I have tried to make quart asyncio stuff working with python3.6 (ubuntu 18.04LTS and opencv dep stuff)

```
@app.websocket('/ws0')
@collect_websocket
async def ws(queue):
    producer = asyncio.create_task(sending(queue))
    consumer = asyncio.create_task(receiving())
    await asyncio.gather(producer, consumer)

@app.before_serving
async def startup():
    app.beacon_task = asyncio.create_task(beacon_json())


### (3.7 working!) -> change to ->(3.6 not working!)


@app.websocket('/ws0')
@collect_websocket
async def ws(queue):
    loop = asyncio.get_event_loop()
    producer = loop.create_task(sending(queue))
    consumer = loop.create_task(receiving())
    await asyncio.gather(producer, consumer)

@app.before_serving
async def startup():
    loop = asyncio.get_event_loop()
    app.beacon_task = loop.create_task(beacon_json())
```

I have also tried `copy_current_request_context`, didn't work either, can someone pointing some directions?

**Comment by pgjones** [comment]
Hi @c2h2, there isn't a supported version of Quart that supports Python3.6 so I'd really encourage you to switch to Python3.7 or later. 

In what way does the code above not work? Does it fault with an exception, not do something?

**Comment by c2h2** [comment]
Hi @pgjones Thanks, one of the errors is (there are other messages):

```
root@dev:/opt/darknet/quart_websocket_example# python3 simple_multi_user_chat.py
Running on https://127.0.0.1:5000 (CTRL + C to quit)
[2019-12-05 14:02:54,896] ASGI Framework Lifespan error, continuing without Lifespan support
[2019-12-05 14:02:55,046] 127.0.0.1:36280 POST /api/upload 1.1 404 103 1347
Exception in callback H11Server.recycle_or_close(<Task finishe...> result=None>)
handle: <Handle H11Server.recycle_or_close(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/hypercorn/asyncio/h11.py", line 104, in recycle_or_close
    self.connection.start_next_cycle()
  File "/usr/local/lib/python3.6/dist-packages/h11/_connection.py", line 206, in start_next_cycle
    self._cstate.start_next_cycle()
  File "/usr/local/lib/python3.6/dist-packages/h11/_state.py", line 301, in start_next_cycle
    "not in a reusable state. self.states={}".format(self.states)
h11._util.LocalProtocolError: not in a reusable state. self.states={CLIENT: SEND_BODY, SERVER: DONE}

```

quart is really cool! I will figure a way to upgrade to 3.7 with Ubuntu 18.04 and opencv bindings.

**Comment by pgjones** [comment]
I've fixed an error very similar (hopefully the same) in a more recent Hypercorn release - 0.5 of Hypercorn was the last to support Python3.6. 

Glad Quart is useful to you, hopefully you can upgrade and carry on.
