### ISSUE TITLE
Unable to serve static file

### ISSUE THREAD

**Issue by basilfx** [pgjones/quart#94]
I have a very simple application set-up, that I run 'manually':

```python
async def run(loop):
    app = Quart(__name__, template_folder="www/", static_folder="www/static/")

    @app.route("/")
    async def view_index():
        return await render_template("index.html")

    await app.run_task(host="0.0.0.0", debug=True)
```

The `index.html` requests `/static/main.css`. That file exists (verified), but it cannot be served:

```
[2020-02-07 22:10:07,395] ERROR in app: Exception on request GET /static/main.css
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/quart/app.py", line 1774, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/env/lib/python3.7/site-packages/quart/app.py", line 1796, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/env/lib/python3.7/site-packages/quart/app.py", line 1082, in handle_user_exception
    raise error
  File "/env/lib/python3.7/site-packages/quart/app.py", line 1794, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/env/lib/python3.7/site-packages/quart/app.py", line 1842, in dispatch_request
    return await handler(**request_.view_args)
  File "/env/lib/python3.7/site-packages/quart/static.py", line 87, in send_static_file
    return await send_from_directory(self.static_folder, filename)
  File "/env/lib/python3.7/site-packages/quart/static.py", line 171, in send_from_directory
    last_modified=last_modified,
  File "/env/lib/python3.7/site-packages/quart/static.py", line 242, in send_file
    await response.make_conditional(request.range)
  File "/env/lib/python3.7/site-packages/quart/wrappers/response.py", line 381, in make_conditional
    if len(request_range.ranges) == 0:  # Not a conditional request
AttributeError: 'NoneType' object has no attribute 'ranges'
```

When debugging, I checked `request.range` in `quart/static.py:242`, which is `None`. That `request.range` is passed-on to the `make_conditional` in `quart/wrappers/response.py:381` as `request_range`, where it's `None` as well. There seems to be a check for if a ranger header is available (`if len(request_range.ranges) == 0`), but I guess that doesn't work properly.

Running using version `0a56a32090b7cc7f0faa27845225af3158e83c87`, but also an older version (somewhere last week) did not work. If I disable the call to `make_conditional` in `quart/static.py:242`, it works fine.

**Comment by pgjones** [comment]
Thanks (this was very clear), I've fixed in 3e9fd2d0a0ff1acbba8552b7321f56f1f7d68478.
