### ISSUE TITLE
ImportError: cannot import name 'ROUTE_VAR_RE' from 'quart.routing

### ISSUE THREAD

**Issue by n-nedkov-premfina** [pgjones/quart#95]
Hello people,

After installing quart 0.11.1 I've got the following error on starting the application:

`ImportError: cannot import name 'ROUTE_VAR_RE' from 'quart.routing`

Do I need to update something in the project?

"Edit" here it is the traceback seems it is from the quart-openapi:
```
Traceback (most recent call last):
  File "C:/Development/be__cms/v1/__main__.py", line 2, in <module>
    from python_core.libraries.application import Application
  File "C:\Development\be__cms\venv\lib\site-packages\python_core\libraries\application.py", line 6, in <module>
    from ..libraries.server.rest import ApplicationBuilder
  File "C:\Development\be__cms\venv\lib\site-packages\python_core\libraries\server\rest.py", line 2, in <module>
    from quart_openapi import Pint
  File "C:\Development\be__cms\venv\lib\site-packages\quart_openapi\__init__.py", line 4, in <module>
    from .swagger import Swagger
  File "C:\Development\be__cms\venv\lib\site-packages\quart_openapi\swagger.py", line 1, in <module>
    from quart.routing import ROUTE_VAR_RE, Map as RouteMap
ImportError: cannot import name 'ROUTE_VAR_RE' from 'quart.routing' (C:\Development\be__cms\venv\lib\site-packages\quart\routing.py)
```

We will update our projects to use quart 0.10.0 until it is fixed. Please notify me here when it is fixed. :)

**Comment by pgjones** [comment]
This is an issue with Quart-OpenAPI, please follow this [issue](https://github.com/factset/quart-openapi/issues/38) for updates.
